"""Public models for OCR text-region colour estimation."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


@dataclass(frozen=True, slots=True)
class RgbaColour:
    """One observed non-premultiplied sRGB colour.

    Attributes:
        red: Red channel as an integer from 0 through 255 inclusive.
        green: Green channel as an integer from 0 through 255 inclusive.
        blue: Blue channel as an integer from 0 through 255 inclusive.
        alpha: Opacity as an integer from 0 through 255 inclusive, where 0 is fully
            transparent and 255 is fully opaque.

    The value is the source image's observed stored RGBA colour. It is not an
    attempt to infer a hidden, pre-composited layer colour.
    """

    red: int
    green: int
    blue: int
    alpha: int = 255

    def __post_init__(self) -> None:
        for channel_name, channel_value in (
            ("red", self.red),
            ("green", self.green),
            ("blue", self.blue),
            ("alpha", self.alpha),
        ):
            if not 0 <= channel_value <= 255:
                message = f"{channel_name} must be between 0 and 255 inclusive."
                raise ValueError(message)


class BackgroundKind(str, Enum):
    """Advisory classification of the local background.

    ``FLAT`` has low local colour variation, ``GRADIENT`` has variation that the
    estimator considers smooth, and ``COMPLEX`` is neither. This classification
    does not provide background reconstruction data.
    """

    FLAT = "flat"
    GRADIENT = "gradient"
    COMPLEX = "complex"


@dataclass(frozen=True, slots=True)
class TextRegionColourEstimate:
    """Estimated colours and reliability signals for one OCR text region.

    Attributes:
        text_colour: Estimated primary text-fill colour as observed in the source
            image.
        background_colour: Estimated immediate surface behind the glyphs, such as a
            label panel. It is not enough to reconstruct a gradient or complex
            background.
        text_colour_confidence: A normalized 0.0--1.0 heuristic reliability score.
            It combines the text mask's coverage, text/background Lab contrast, and
            consistency of the selected text-colour cluster. It is neither a
            probability nor OCR confidence. Low values should trigger review or a
            caller-selected fallback.
        background_colour_confidence: A normalized 0.0--1.0 heuristic reliability
            score. It combines immediate-background support and consistency. It is
            neither a probability nor OCR
            confidence. Low values should trigger review or a caller-selected
            fallback.
        background_kind: Advisory local-background complexity classification.
    Confidence values are comparable only among estimates generated by the same
    estimator version. A score of 0.0 means no usable supporting evidence; 1.0 means
    the strongest evidence available to this heuristic, not guaranteed correctness.
    """

    text_colour: RgbaColour
    background_colour: RgbaColour
    text_colour_confidence: float
    background_colour_confidence: float
    background_kind: BackgroundKind

    def __post_init__(self) -> None:
        for confidence_name, confidence_value in (
            ("text_colour_confidence", self.text_colour_confidence),
            ("background_colour_confidence", self.background_colour_confidence),
        ):
            if not 0.0 <= confidence_value <= 1.0:
                message = f"{confidence_name} must be between 0.0 and 1.0 inclusive."
                raise ValueError(message)
